spring:
  redis:
    host: 120.79.47.111
    port: 30379
    password: 2aVzLk8jcmJHh8Xo
  datasource:
    url: jdbc:mysql://qa.tidb.hcyy.top:4000/mutants_bi?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456