spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://qa.tidb.hcyy.top:4000/mutants_bi?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456