spring:
  redis:
    sentinel:
      nodes: 192.168.13.50:20190,192.168.13.50:20191,192.168.13.50:20192
      master: mymaster
  datasource:
    url: jdbc:mysql://192.168.13.60:3306/esc?useUnicode=true&characterEncoding=utf8
    username: root
    password: root