spring:
  redis:
    host: 120.79.47.111
    port: 30379
    password: 2aVzLk8jcmJHh8Xo
  datasource:
    url: jdbc:mysql://120.79.47.111:3307/esc?useUnicode=true&characterEncoding=utf8
    username: esc
    password: d8Mo9u1JroPbKtXG