spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/esc?useUnicode=true&characterEncoding=utf8
    username: root
    password: root