spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      pool-name: ESC-POOL
      connection-test-query: SELECT 1 FROM DUAL
  profiles:
    active: dev
liquibase:
  change-log: classpath:db-changelog.xml
mybatis-plus:
  mapper-locations: classpath*:sqlmap/*Mapper.xml
  typeAliasesPackage: com.cc.etherscan.io.entity
  #实体扫描，多个package用逗号或者分号分隔
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    db-type: mysql
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
scheduling:
  enabled: true
etherscan:
  pageSize: 100
  startPage: 1
  totalPage: 1
  threadCount: 1
  intervalSeconds: 1
  scanIntervalCron: 0 0/30 * * * ?